In [23]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [3]:
a=np.array([[1,2,3,4],[5,5,6,7],[1,4,2,3],[5,3,2,1],[8,1,2,2]])
print(a)

[[1 2 3 4]
 [5 5 6 7]
 [1 4 2 3]
 [5 3 2 1]
 [8 1 2 2]]


In [27]:
colnames=["s1","s2","s3","s4"]
rownames=["a","b","c","d","e"]
table=pd.DataFrame(a,index=rownames,columns=colnames)
print(table)

   s1  s2  s3  s4
a   1   2   3   4
b   5   5   6   7
c   1   4   2   3
d   5   3   2   1
e   8   1   2   2


In [28]:
z=(table-table.mean())/table.std()                  #step1
z

s1        s2        s3        s4
a -1.000000 -0.632456  0.000000  0.260623
b  0.333333  1.264911  1.732051  1.563740
c -1.000000  0.632456 -0.577350 -0.173749
d  0.333333  0.000000 -0.577350 -1.042493
e  1.333333 -1.264911 -0.577350 -0.608121

In [12]:
x=np.matrix(z)#step2/3
c=(x-np.mean(x)).T*(x-np.mean(x))/(len(x))
eig_val,eig_vec=np.linalg.eig(c)

In [34]:
print(eig_val.argsort()[::-1])                          #step4

[0 1 2 3]


In [35]:
eig_val

array([2.01263459, 0.8522308 , 0.31510964, 0.02002497])

In [36]:
eig_vec

matrix([[ 0.16195986, -0.91705888, -0.30707099,  0.19616173],
        [-0.52404813,  0.20692161, -0.81731886,  0.12061043],
        [-0.58589647, -0.3205394 ,  0.1882497 , -0.72009851],
        [-0.59654663, -0.11593512,  0.44973251,  0.65454704]])

In [37]:
v=eig_vec[0:,0:2]                                        #step5
v

matrix([[ 0.16195986, -0.91705888],
        [-0.52404813,  0.20692161],
        [-0.58589647, -0.3205394 ],
        [-0.59654663, -0.11593512]])

In [33]:
d=x*v                                                        #step6
d

matrix([[ 1.40033078e-02,  7.55974765e-01],
        [-2.55653399e+00, -7.80431775e-01],
        [-5.14801919e-02,  1.25313470e+00],
        [ 1.01415002e+00,  2.38808310e-04],
        [ 1.57986086e+00, -1.22891650e+00]])